# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_DOCK)		+= dock_switch.o
obj-$(CONFIG_ROTATELOCK)	+= rotationlock_switch.o
obj-$(CONFIG_PSENSOR)		+= psensor_switch.o
obj-$(CONFIG_SIMDETECT)         += simdetect_switch.o
